%% Wyvern — Example 4: Multi-Agent Orchestration
% Coordinate multiple specialised agents to solve a complex problem.
% Requires an OpenAI or Anthropic API key in server/.env.

%% Setup
% wyvern.setup()   % uncomment on first run

%% Create specialised agents
wyvern.agent.create("data_analyst", ...
    model       = "gpt-4o", ...
    systemPrompt= ["You are a data analysis expert specialising in signal " ...
                   "processing. Extract key insights from data descriptions."], ...
    memory      = false)

wyvern.agent.create("report_writer", ...
    model       = "gpt-4o", ...
    systemPrompt= ["You are a technical writer. Produce concise, structured " ...
                   "engineering reports from analysis summaries."], ...
    memory      = false)

wyvern.agent.create("code_generator", ...
    model       = "gpt-4o", ...
    systemPrompt= ["You are a MATLAB expert. Generate clean, well-commented " ...
                   "MATLAB code snippets when given a task description."], ...
    memory      = false)

%% Example pipeline: Analyse → Write → Code
rawData = "A 1024-point vibration signal sampled at 10 kHz. " + ...
          "Peaks detected at 120 Hz, 240 Hz, and 480 Hz. " + ...
          "RMS amplitude 0.45 m/s^2. SNR approximately 22 dB.";

% Step 1: Analysis agent extracts insights
analysis = wyvern.agent.run("data_analyst", ...
    "Analyse this vibration signal measurement: " + rawData);
fprintf("=== Analysis ===\n%s\n\n", analysis)

% Step 2: Report writer structures the findings
report = wyvern.agent.run("report_writer", ...
    "Write a structured technical summary of this analysis:\n" + analysis);
fprintf("=== Report ===\n%s\n\n", report)

% Step 3: Code generator produces MATLAB implementation
code = wyvern.agent.run("code_generator", ...
    "Write MATLAB code to process a vibration signal with " + ...
    "these characteristics:\n" + analysis);
fprintf("=== MATLAB Code ===\n%s\n\n", code)

%% Memory-enabled multi-turn session
wyvern.agent.create("tutor", ...
    model       = "gpt-4o", ...
    systemPrompt= "You are a patient MATLAB and DSP tutor.", ...
    memory      = true)

wyvern.agent.run("tutor", "I want to learn about digital filters.");
wyvern.agent.run("tutor", "What is the difference between FIR and IIR?");
wyvern.agent.run("tutor", "Show me a MATLAB example of the first type you mentioned.");
% The tutor remembers that FIR was mentioned first.

%% Clean up
wyvern.agent.reset("tutor")
